-- Solution Exercise 27 --
SELECT 
    SUM(CITY.POPULATION) 
FROM CITY 
INNER JOIN COUNTRY 
ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE COUNTRY.CONTINENT = 'Asia';

-- Solution Exercise 28 --
SELECT 
	CITY.NAME 
FROM CITY 
INNER JOIN COUNTRY 
ON CITY.COUNTRYCODE = COUNTRY.CODE 
WHERE CONTINENT = 'Africa';

-- Solution Exercise 29 --
SELECT 
	COUNTRY.CONTINENT, FLOOR(AVG(CITY.POPULATION))
FROM CITY 
INNER JOIN COUNTRY 
ON CITY.COUNTRYCODE = COUNTRY.CODE 
GROUP BY COUNTRY.CONTINENT;