-- Solution Exercise 1 --
SELECT * FROM CITY 
WHERE COUNTRYCODE = 'USA' AND POPULATION > 100000;

-- Solution Exercise 2 --
SELECT NAME FROM CITY 
WHERE COUNTRYCODE = 'USA' AND POPULATION > 120000;

-- Solution Exercise 3 --
SELECT CITY, STATE FROM STATION;

-- Solution Exercise 4 --
SELECT DISTINCT CITY FROM STATION 
WHERE ID % 2 = 0; 

-- Another Solution Exercise 4 --
SELECT DISTINCT CITY FROM STATION 
WHERE MOD(ID, 2) = 0; 

-- Solution Exercise 5 --
SELECT COUNT(CITY) - COUNT(DISTINCT (CITY)) FROM STATION;

-- Solution Exercise 6 with 2 queries --
SELECT CITY, LENGTH(CITY) FROM STATION
WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY))FROM STATION)
GROUP BY CITY 
ORDER BY CITY ASC
LIMIT 1;

SELECT CITY, LENGTH(CITY) FROM STATION
WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY))FROM STATION)
GROUP BY CITY 
ORDER BY CITY ASC
LIMIT 1;

-- Solution Exercise 6 with 1 query --
SELECT CITY, LENGTH(CITY) FROM STATION
WHERE CITY = (SELECT CITY FROM STATION ORDER BY LENGTH(CITY) ASC, CITY LIMIT 1)
OR CITY = (SELECT CITY FROM STATION ORDER BY LENGTH(CITY) DESC, CITY LIMIT 1);

-- Solution Exercise 7 --
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%';

-- Solution Exercise 8 --
SELECT DISTINCT CITY FROM STATION
WHERE (CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%') 
AND (CITY LIKE '%A' OR CITY LIKE '%E' OR CITY LIKE '%I' OR CITY LIKE '%O' OR CITY LIKE '%U');

-- Solution Exercise 9 --
SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT LIKE 'A%' AND CITY NOT LIKE 'E%' AND CITY NOT LIKE 'I%' AND CITY NOT LIKE 'O%' AND CITY NOT LIKE 'U%';

-- Solution Exercise 10 --
SELECT DISTINCT CITY FROM STATION
WHERE (CITY NOT LIKE 'A%' AND CITY NOT LIKE 'E%' AND CITY NOT LIKE 'I%' AND CITY NOT LIKE 'O%' AND CITY NOT LIKE 'U%') 
OR (CITY NOT LIKE '%A' AND CITY NOT LIKE '%E' AND CITY NOT LIKE '%I' AND CITY NOT LIKE '%O' AND CITY NOT LIKE '%U');

-- Solution Exercise 11 --
SELECT Name FROM STUDENTS
WHERE Marks > 75
ORDER BY RIGHT(Name,3),ID;

-- Another Solution Exercise 11 --
SELECT Name FROM STUDENTS
WHERE Marks > 75
ORDER BY SUBSTRING(Name,(LENGTH(Name)-2),3), ID;
